version: "3"

services:

    db:
        image: postgres:latest
        environment:
          - POSTGRES_USER=dbc
          - POSTGRES_PASSWORD=dbc
          - POSTGRES_DB=fab_demo_02
        ports:
          - "5433:5432"
        volumes:
          - ./pgdb_fab_02:/var/lib/postgresql/data

